language: ruby

before_install:
- rvm gemset use global
- gem uninstall bundler -Iax --version '<1.14'
- gem install bundler -v 1.12.5

script:
- bundle exec rake clean rubocop test install TESTOPTS='--verbose'

cache: bundler

rvm:
  - 2.2

sudo: required

addons:
  apt:
    packages:
    - dnsutils

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email:
    on_success: never
